# Site settings
title: Carlos Alexandre Costa
email: c.alexandre241@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://carl1988a.github.io/" # the base hostname & protocol for your site

linkedin_username: linkedin.com/in/carlosalexandre-costa
github_username: Carl1988A

# Build settings
markdown: kramdown
